create table google_suggest_clone_data (
    search_term     varchar(100),
    num_results     int,

    primary key (search_term)
);
insert into google_suggest_clone_data values ('amazon', 1300000);
insert into google_suggest_clone_data values ('ask jeeves', 425990);
insert into google_suggest_clone_data values ('argos', 2523);
insert into google_suggest_clone_data values ('aol', 234234);
insert into google_suggest_clone_data values ('aim express', 98753);
insert into google_suggest_clone_data values ('adaware', 5431);
insert into google_suggest_clone_data values ('amazon.com', 1);
insert into google_suggest_clone_data values ('american idol', 563400);
insert into google_suggest_clone_data values ('american airlines', 32453);
insert into google_suggest_clone_data values ('aim', 245345);
insert into google_suggest_clone_data values ('bbc', 34532);
insert into google_suggest_clone_data values ('best buy', 234523);
insert into google_suggest_clone_data values ('bank of america', 74754);
insert into google_suggest_clone_data values ('baby names', 5632);
insert into google_suggest_clone_data values ('blockbuster', 23655);
insert into google_suggest_clone_data values ('british airways', 2300);
insert into google_suggest_clone_data values ('barnes and noble', 245423);
insert into google_suggest_clone_data values ('bmi', 24534678);
insert into google_suggest_clone_data values ('britney spears', 34534);
insert into google_suggest_clone_data values ('currency converter', 34467);
insert into google_suggest_clone_data values ('cnn', 8974);
insert into google_suggest_clone_data values ('cars', 24523);
insert into google_suggest_clone_data values ('circuit city', 12434);
insert into google_suggest_clone_data values ('costco', 4878);
insert into google_suggest_clone_data values ('cheap flights', 2221);
insert into google_suggest_clone_data values ('chinese new year', 12340);
insert into google_suggest_clone_data values ('cingular', 3242348);
insert into google_suggest_clone_data values ('cbbc', 36735);
insert into google_suggest_clone_data values ('continental airlines', 3673);
insert into google_suggest_clone_data values ('dictionary', 89632544);
insert into google_suggest_clone_data values ('dell', 3245);
insert into google_suggest_clone_data values ('dictionary.com', 1);
insert into google_suggest_clone_data values ('dogs', 45345);
insert into google_suggest_clone_data values ('disney', 2234);
insert into google_suggest_clone_data values ('delta airlines', 2679);
insert into google_suggest_clone_data values ('dvd shrink', 67543);
insert into google_suggest_clone_data values ('delta', 122000000);
insert into google_suggest_clone_data values ('desperate housewizes', 235600);
insert into google_suggest_clone_data values ('download.com', 1);
insert into google_suggest_clone_data values ('ebay', 345000);
insert into google_suggest_clone_data values ('expedia', 45347);
insert into google_suggest_clone_data values ('easyjet', 24545);
insert into google_suggest_clone_data values ('espn', 254566);
insert into google_suggest_clone_data values ('ebay.com', 1);
insert into google_suggest_clone_data values ('exchange rates', 2333);
insert into google_suggest_clone_data values ('ebay uk', 5698);
insert into google_suggest_clone_data values ('eminem', 22213);
insert into google_suggest_clone_data values ('php', 3214000);
insert into google_suggest_clone_data values ('phpbb', 768700);
insert into google_suggest_clone_data values ('phpmyadmin', 324544);
insert into google_suggest_clone_data values ('php tutorial', 98757);
insert into google_suggest_clone_data values ('php nuke', 99000);
insert into google_suggest_clone_data values ('php scripts', 56660);
insert into google_suggest_clone_data values ('phpnuke', 22);
insert into google_suggest_clone_data values ('php tutorials', 300000000);
insert into google_suggest_clone_data values ('php mysql', 122200);
insert into google_suggest_clone_data values ('php date', 236660);
insert into google_suggest_clone_data values ('javascript', 333444);
insert into google_suggest_clone_data values ('javascript tutorial', 776673);
insert into google_suggest_clone_data values ('javascript reference', 567899);
insert into google_suggest_clone_data values ('javascript array', 99880);
insert into google_suggest_clone_data values ('javascript alert', 12367);
insert into google_suggest_clone_data values ('javascript window.open', 45645);
insert into google_suggest_clone_data values ('javascript redirect', 2390);
insert into google_suggest_clone_data values ('javascript substring', 982);
insert into google_suggest_clone_data values ('javascript tutorials', 23480);
insert into google_suggest_clone_data values ('xmlhttprequest', 20440);
insert into google_suggest_clone_data values ('xmlhttp', 234390);
insert into google_suggest_clone_data values ('xmlhttp javascript', 32760);
insert into google_suggest_clone_data values ('xmlhttp post', 23847);
insert into google_suggest_clone_data values ('xmlhttp open', 239834980);
insert into google_suggest_clone_data values ('xmlhttp object', 234000);
